name: Release cache build
on:
  push:
    branches: [main]
    tags:
      - "**[0-9]+.[0-9]+.[0-9]+*"
jobs:
  nix-build-cache:
    strategy:
      fail-fast: false
      matrix:
        include:
          - runner: ubuntu-latest
            system: x86_64-linux
            qemu: false
          - runner: ubuntu-latest
            system: aarch64-linux
            qemu: true
          - runner: macos-15
            system: x86_64-darwin
            qemu: false
          - runner: macos-15-arm64
            system: aarch64-darwin
            qemu: false
    runs-on: ${{ matrix.runner }}
    steps:
      - uses: actions/checkout@v4
      - name: Enable qemu for aarch64
        if: matrix.qemu == true
        run: |
          sudo apt-get update
          sudo apt-get install -y qemu-user-static binfmt-support
          sudo update-binfmts --enable qemu-aarch64
      - uses: cachix/install-nix-action@v27
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: |
            experimental-features = nix-command flakes
            ${ matrix.qemu == true && 'extra-platforms = aarch64-linux' || '' }
      - uses: cachix/cachix-action@v14
        with:
          name: flk-cache
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - name: Build flake package
        run: nix build .#flk --impure
